### DISCUSSION TITLE
Logs are never pushed with docker-compose

### DISCUSSION THREAD

**Discussion by nhatmvo** [serilog-contrib/serilog-sinks-grafana-loki#149] [Q&A] [answered]
I'm using .NET 6
Serilog.Sinks.Grafana.Loki v8.0.1
I'm trying to implement Grafana Loki following with this article: https://medium.com/c-sharp-progarmming/net-core-microservice-logging-with-grafana-and-loki-92cd2783ed88
but it seems like the logs never push into loki. here's my code from Program.cs file:
````
var builder = WebApplication.CreateBuilder(args);

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Override("Microsoft", Serilog.Events.LogEventLevel.Warning)
    .Enrich.FromLogContext()
    .WriteTo.Console()
    .CreateLogger();

....
builder.Host.UseSerilog((ctx, cfg) =>
{
    cfg.Enrich.WithProperty("Application", ctx.HostingEnvironment.ApplicationName)
        .Enrich.WithProperty("Environment", ctx.HostingEnvironment.EnvironmentName)
        .WriteTo.Console(new RenderedCompactJsonFormatter())
        .WriteTo.GrafanaLoki(ctx.Configuration["loki"]);
});

....
app.UseSerilogRequestLogging();
````

docker-compose file is pretty much like the article above:
```
`version: '3.4'

services:
  lokigraf.api:
    image: ${DOCKER_REGISTRY-}dotnetgrafanalokiapi
    build:
      context: .
      dockerfile: dotnet.GrafanaLoki.API/Dockerfile
    environment:
        loki: http://loki:3100
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: https://+:443;http://+:80
    ports:
        - 8085:80
        - 8086:443
    depends_on:
        loki:
            condition: service_healthy

  loki:
    container_name: loki
    image: grafana/loki:master
    ports:
       - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
        test: wget -q --tries=1 -O- http://localhost:3100/ready 
        interval: 3s
        timeout: 3s
        retries: 10
        start_period: 10s

  grafana:
    container_name: grafana
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    depends_on:
        loki:
            condition: service_healthy`
```
it still works when using Serilog to log to the console (I've checked within container logs), and I've tried SelfLog but having no error neither. what am I missing here?
